### ISSUE TITLE
Call generateHash with charset

### ISSUE THREAD

**Issue by pablosichert** [tkc/vue-image-uploader#8]
Just wanted to let you know that you can use the [`random-hash`](https://github.com/PabloSichert/random-hash) library like this

```js
const hash = generateHash({ charset: 'ABC...' });
```

instead of

https://github.com/tkc/vue-image-uploader/blob/32d007f7a568957a69dfbc2a85a2a4cc7e366945/src/lib/ChangeImage.vue#L119-L120

🌞

**Comment by tkc** [comment]
@PabloSichert 

Thanks !
random-hash is nice.　( ´∀｀)
I will correct it.
